const String supabaseUrl = 'https://jrtsthzgascmtiivwapb.supabase.co';
const String supabaseAnonKey =
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpydHN0aHpnYXNjbXRpaXZ3YXBiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NzQ0MTAsImV4cCI6MjA3MDE1MDQxMH0.7DtrOqgZvzPXzYeP3SdnFddnL14lgVdQiKwhPO9WRNI';
